// Mocks generated by Mockito 5.4.4 from annotations
// in alo/test/training_flow/repository/training_flow_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:alo/training_flow/domain/entitys/coach_entity.dart' as _i4;
import 'package:alo/training_flow/domain/entitys/training_flow_class.dart'
    as _i5;
import 'package:alo/training_flow/domain/entitys/training_flow_entity.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TrainingFlowEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrainingFlowEntity extends _i1.Mock
    implements _i2.TrainingFlowEntity {
  MockTrainingFlowEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  String get coverImage => (super.noSuchMethod(
        Invocation.getter(#coverImage),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#coverImage),
        ),
      ) as String);

  @override
  String get seriesName => (super.noSuchMethod(
        Invocation.getter(#seriesName),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#seriesName),
        ),
      ) as String);

  @override
  String get coachesName => (super.noSuchMethod(
        Invocation.getter(#coachesName),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#coachesName),
        ),
      ) as String);

  @override
  String get description => (super.noSuchMethod(
        Invocation.getter(#description),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
      ) as String);

  @override
  String get overviewVideo => (super.noSuchMethod(
        Invocation.getter(#overviewVideo),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#overviewVideo),
        ),
      ) as String);

  @override
  List<_i4.CoachEntity> get coaches => (super.noSuchMethod(
        Invocation.getter(#coaches),
        returnValue: <_i4.CoachEntity>[],
      ) as List<_i4.CoachEntity>);

  @override
  List<_i5.TrainingFlowClass> get classes => (super.noSuchMethod(
        Invocation.getter(#classes),
        returnValue: <_i5.TrainingFlowClass>[],
      ) as List<_i5.TrainingFlowClass>);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);
}
